#!/usr/bin/env python

"""
A program that lists URLs with changes for a given Wikipedia article.

Sample usage:

./dl-revisions.py Nmap

AUTHOR: Jacek Wielemborek, licensed under WTFPL.
"""

from lxml import html
import urllib
import sys

inurl = sys.argv[1] + '&limit=10000'
while True:
    t = html.parse(urllib.urlopen(inurl))
    for a in t.xpath('//a [@class="mw-changeslist-date"]'):
        url = 'https://en.wikipedia.org' + a.get('href') + '&action=edit'
        print(url)
    n = t.xpath('//a [@rel="next"]')
    if n:
        inurl = 'https://en.wikipedia.org/' + n[0].get('href')
    else:
        break
