#!/usr/bin/env python

"""
A program that lists URLs with changes for a given Wikipedia article.

Sample usage:

./dl-revisions.py Nmap

AUTHOR: Jacek Wielemborek, licensed under WTFPL.
"""

from lxml import html
import urllib
import sys

inurl = 'https://en.wikipedia.org/w/index.php?title=%s&limit=500&action=history' % sys.argv[1]
while True:
    t = html.parse(urllib.urlopen(inurl))
    for a in t.xpath('//a [@class="mw-changeslist-date"]'):
        url = 'https://en.wikipedia.org' + a.get('href') + '&action=edit'
        print(url)
    n = t.xpath('//a [contains(.,"older 500")]')
    if n:
        inurl = 'https://en.wikipedia.org/' + n[0].get('href')
    else:
        break
